site_name: "Andy Boutte's Documentation"
site_url: 'http://docs.andyboutte.com'
site_description: "Andy Boutte's Documentation"
site_author: 'Andy Boutte'
repo_name: 'docs'
repo_url: 'https://github.com/aboutte/docs'
remote_name: 'mine'
theme: 'material'
extra:
  feature:
    tabs: false
  palette:
    primary: 'red'
    accent: 'pink'
  social:
    - type: 'github'
      link: 'https://github.com/aboutte'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/aboutte'
google_analytics:
  - 'UA-111549698-1'
  - 'auto'
